creation_rules:
  - path_regex: hosts/global/secrets/.*\.(yaml|yml|env)$ 
    key_groups:
      - age:
          - "age1tqs7lhtlj788e8a7h34p49s2wqlhft24zwugyrcstg66xffev9gsjssl2y"
          - "age1gckx4jj3afv57f5pr00jcwr9eptvuetvpcu9sckn4sp6vk32hgnqmplqaf"
          - "age1pq4jcwlg7k59x533vgnt2qxzs5yxndey3keexagp03p09276ufds2m8fuf"
          - "age17p0nnscuym0ywqdlrhays58u2jj0pwjdu730tawrsvyg97ceuqzqdlpc94"
