# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."OpenBooks" = {
    image = "evanbuss/openbooks:latest";
    volumes = [
      "/data/kavita/books/openbooks:/books:rw"
    ];
    ports = [
      "8085:80/tcp"
    ];
    cmd = [ "--persist" "--name" "jabuxas" "-s" "irc.irchighway.net:9999" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=openbooks"
      "--network=openbooks_default"
    ];
  };
  systemd.services."docker-OpenBooks" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-openbooks_default.service"
    ];
    requires = [
      "docker-network-openbooks_default.service"
    ];
    partOf = [
      "docker-compose-openbooks-root.target"
    ];
    wantedBy = [
      "docker-compose-openbooks-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-openbooks_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f openbooks_default";
    };
    script = ''
      docker network inspect openbooks_default || docker network create openbooks_default
    '';
    partOf = [ "docker-compose-openbooks-root.target" ];
    wantedBy = [ "docker-compose-openbooks-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-openbooks-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
