{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."cloudflare-ddns" = {
    image = "timothyjmiller/cloudflare-ddns:latest";
    environment = {
      "DELETE_ON_STOP" = "false";
      "EMOJI" = "true";
      "IP4_DOMAINS" = "jabuxas.com";
      "IP6_PROVIDER" = "none";
      "PROXIED" = "!sub(intra.jabuxas.com,*.jabuxas.com)";
      "TTL" = "1";
      "UPDATE_CRON" = "@every 5m";
      "UPDATE_ON_START" = "true";
    };
    environmentFiles = [
      config.sops.secrets.cloudflare_ddns_env.path
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
      "--security-opt=no-new-privileges:true"
    ];
  };
  systemd.services."docker-cloudflare-ddns" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-ddns-root.target"
    ];
    wantedBy = [
      "docker-compose-ddns-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-ddns-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
