# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."kavita" = {
    image = "jvmilazz0/kavita:latest";
    environment = {
      "TZ" = "America/Sao_Paulo";
    };
    volumes = [
      "/home/you/services/kavita/books:/books:rw"
      "/home/you/services/kavita/comics:/comics:rw"
      "/home/you/services/kavita/data:/kavita/config:rw"
      "/home/you/services/kavita/manga:/manga:rw"
    ];
    ports = [
      "5000:5000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=kavita"
      "--network=kavita_default"
    ];
  };
  systemd.services."docker-kavita" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-kavita_default.service"
    ];
    requires = [
      "docker-network-kavita_default.service"
    ];
    partOf = [
      "docker-compose-kavita-root.target"
    ];
    wantedBy = [
      "docker-compose-kavita-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-kavita_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f kavita_default";
    };
    script = ''
      docker network inspect kavita_default || docker network create kavita_default
    '';
    partOf = [ "docker-compose-kavita-root.target" ];
    wantedBy = [ "docker-compose-kavita-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-kavita-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
