# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."refinement-web-server" = {
    image = "ghcr.io/jabuxas/refinement:latest";
    environment = {
      "ROCKET_ADDRESS" = "0.0.0.0";
    };
    volumes = [
      "/home/you/services/refinement/projects:/projects:rw"
    ];
    ports = [
      "8880:8000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=web-server"
      "--network=refinement_default"
    ];
  };
  systemd.services."docker-refinement-web-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-refinement_default.service"
    ];
    requires = [
      "docker-network-refinement_default.service"
    ];
    partOf = [
      "docker-compose-refinement-root.target"
    ];
    wantedBy = [
      "docker-compose-refinement-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-refinement_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f refinement_default";
    };
    script = ''
      docker network inspect refinement_default || docker network create refinement_default
    '';
    partOf = [ "docker-compose-refinement-root.target" ];
    wantedBy = [ "docker-compose-refinement-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-refinement-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
