# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."abyss-paste" = {
    image = "ghcr.io/jabuxas/abyss:latest";
    environmentFiles = [ config.sops.secrets.abyss_environment.path ];
    volumes = [
      "/home/you/services/abyss/files:/app/files:rw"
    ];
    ports = [
      "3235:3235/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=paste"
      "--network=abyss_default"
    ];
  };
  systemd.services."docker-abyss-paste" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-abyss_default.service"
    ];
    requires = [
      "docker-network-abyss_default.service"
    ];
    partOf = [
      "docker-compose-abyss-root.target"
    ];
    wantedBy = [
      "docker-compose-abyss-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-abyss_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f abyss_default";
    };
    script = ''
      docker network inspect abyss_default || docker network create abyss_default
    '';
    partOf = [ "docker-compose-abyss-root.target" ];
    wantedBy = [ "docker-compose-abyss-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-abyss-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
