# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."syncthing" = {
    image = "syncthing/syncthing";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
    };
    volumes = [
      "/seagate/services/sync:/var/syncthing:rw"
    ];
    ports = [
      "8384:8384/tcp"
      "22000:22000/tcp"
      "22000:22000/udp"
      "21027:21027/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1"
      "--health-interval=1m0s"
      "--health-retries=3"
      "--health-timeout=10s"
      "--hostname=frigid"
      "--network-alias=syncthing"
      "--network=syncthing_default"
    ];
  };
  systemd.services."docker-syncthing" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-syncthing_default.service"
    ];
    requires = [
      "docker-network-syncthing_default.service"
    ];
    partOf = [
      "docker-compose-syncthing-root.target"
    ];
    wantedBy = [
      "docker-compose-syncthing-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-syncthing_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f syncthing_default";
    };
    script = ''
      docker network inspect syncthing_default || docker network create syncthing_default
    '';
    partOf = [ "docker-compose-syncthing-root.target" ];
    wantedBy = [ "docker-compose-syncthing-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-syncthing-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
