# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."jabuxas_void" = {
    image = "jabuxas/void:latest";
    environment = {
      "NODE_ENV" = "production";
      "TZ" = "America/Sao_Paulo";
    };
    ports = [
      "3000:3000/tcp"
    ];
    user = "1000:1000";
    log-driver = "journald";
    extraOptions = [
      "--cpus=0.5"
      "--health-cmd=[\"wget\", \"--no-verbose\", \"--tries=1\", \"--spider\", \"http://localhost:3000\"]"
      "--health-interval=30s"
      "--health-retries=3"
      "--health-start-period=5s"
      "--health-timeout=5s"
      "--memory-reservation=33554432b"
      "--memory=134217728b"
      "--network-alias=jabuxas-void"
      "--network=web_default"
    ];
  };
  systemd.services."docker-jabuxas_void" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-build-jabuxas_void.service"
      "docker-network-web_default.service"
    ];
    requires = [
      "docker-build-jabuxas_void.service"
      "docker-network-web_default.service"
    ];
    partOf = [
      "docker-compose-web-root.target"
    ];
    wantedBy = [
      "docker-compose-web-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-web_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f web_default";
    };
    script = ''
      docker network inspect web_default || docker network create web_default
    '';
    partOf = [ "docker-compose-web-root.target" ];
    wantedBy = [ "docker-compose-web-root.target" ];
  };

  # Builds
  systemd.services."docker-build-jabuxas_void" = {
    path = [ pkgs.docker pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      TimeoutSec = 300;
    };
    script = ''
      cd /home/you/services/web
      docker build --network=host -t jabuxas/void:latest .
    '';
    partOf = [ "docker-compose-web-root.target" ];
    wantedBy = [ "docker-compose-web-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-web-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
